[env]
_.python.venv = {path = ".venv", create = true}

[hooks]
# enter = ["uv sync --all-extras"]
postinstall = [
  "cp -n .env.sample .env",
  "uv venv --clear",
  "uv sync --refresh",
  "uv run pre-commit install --hook-type pre-push --config etc/pre-commit.yaml"
]

[settings]
env_file = '.env'
experimental = true
idiomatic_version_file_enable_tools = ["python"]
python.compile = false
python.uv_venv_auto = true

[tools]
just = "latest"
uv = "latest"
