[env]
BETTER_EXCEPTIONS = 1
UV_COMPILE_BYTECODE=1
UV_LINK_MODE="copy"
_.python.venv = {path = ".venv", create = true}

[hooks]
# enter = ["uv sync --all-extras"]
# postinstall = ["uv sync --all-extras --upgrade"]

[settings]
env_file = '.env'
experimental = true
idiomatic_version_file_enable_tools = ["python"]
python.compile = false
python.uv_venv_auto = true

# [tools]
# ruff = "latest"
# uv = "latest"
