[unix_http_server]
file = %(ENV_PWD)s/run/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
loglevel  = info
nodaemon  = false
silent    = false
minfds    = 1024
minprocs  = 200
logfile   = %(ENV_PWD)s/log/daemon.log
pidfile   = %(ENV_PWD)s/run/supervisord.pid
directory = %(ENV_PWD)s

[supervisorctl]
prompt       = " >"
history_file = %(ENV_PWD)s/run/supervisord.hist
serverurl    = unix://run/supervisord.sock

; [program:yacron]
; process_name   = %(program_name)s
; command        = uvx yacron -c %(ENV_PWD)s/etc/yacron.yaml
; stdout_logfile = %(ENV_PWD)s/log/%(program_name)s.log
; stderr_logfile = %(ENV_PWD)s/log/errors/%(program_name)s.log
; autostart      = true
; autorestart    = true
; startsecs      = 1
; stopwaitsecs   = 3600
; killasgroup    = true
