---
# defaults:
#     utc: false
#     shell: /bin/bash

#     environment:
#       - key: PATH
#         value: /bin:/usr/bin

jobs:
  - name: example
    command: echo "done!"
    schedule: '*/1 * * * *'
    concurrencyPolicy: Forbid

   # enabled: false
   # captureStderr: true

   # command: |
   #   echo "hello" 1>&2
   #   sleep 1
   #   exit 10

   # schedule:
   #   minute: "*/10"

   # onFailure:
   #   retry:
   #     maximumRetries: 10
   #     initialDelay: 1
   #     maximumDelay: 30
   #     backoffMultiplier: 2

   # onPermanentFailure:
   #   report:
   #     mail:
   #       from: example@foo.com
   #       to: example@bar.com
   #       smtpHost: 127.0.0.1
